import pandas as pd
import sys
import re
from io import StringIO
import contextlib

def execute_python_code(code: str, df: pd.DataFrame) -> str:
    """
    Executes Python code generated by the LLM.
    Robustly extracts code from Markdown blocks to avoid executing conversational text.
    """
    output_buffer = StringIO()
    
    # 🟢 FIX: Use Regex to find content strictly inside ```python ... ```
    # This ignores any text before or after the code block.
    code_match = re.search(r"```python\n(.*?)```", code, re.DOTALL)
    
    if code_match:
        clean_code = code_match.group(1).strip()
    else:
        # Fallback: If no markdown block, assume the whole text is code 
        # (but remove markdown literals if present)
        clean_code = code.replace("```python", "").replace("```", "").strip()

    # Define the execution environment
    local_scope = {"df": df, "pd": pd}
    
    try:
        with contextlib.redirect_stdout(output_buffer):
            exec(clean_code, {}, local_scope)
        
        result = output_buffer.getvalue()
        
        if not result:
            return "Code executed successfully, but printed nothing."
            
        return result.strip()
        
    except Exception as e:
        return f"Error executing code: {str(e)}\n\nAttempted Code:\n{clean_code}"