import pandas as pd
import sys
import re
from io import StringIO
import contextlib

def execute_python_code(code: str, df: pd.DataFrame) -> str:
    """
    Executes Python code generated by the LLM.
    Robustly extracts code from Markdown blocks (python, py, markdown, or plain).
    """
    output_buffer = StringIO()
    
    # 🟢 MNC-GRADE REGEX FIX:
    # This pattern matches ``` followed by ANY word (or no word), 
    # captures the code content, and ends with ```
    # flags=re.DOTALL allows the dot (.) to match newlines
    code_match = re.search(r"```(?:\w+)?\n(.*?)```", code, re.DOTALL)
    
    if code_match:
        clean_code = code_match.group(1).strip()
    else:
        # Fallback: Remove backticks if regex fails
        clean_code = code.replace("```python", "").replace("```", "").strip()

    # Define the execution environment
    local_scope = {"df": df, "pd": pd}
    
    try:
        with contextlib.redirect_stdout(output_buffer):
            exec(clean_code, {}, local_scope)
        
        result = output_buffer.getvalue()
        
        if not result:
            return "Code executed successfully, but printed nothing."
            
        return result.strip()
        
    except Exception as e:
        return f"Error executing code: {str(e)}\n\nAttempted Code:\n{clean_code}"