import os

def create_messy_csv(filename):
    # Ensure directory exists
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    content = """Running Report: Q4 Regional Sales
Generated by: Legacy System v2.0
CONFIDENTIAL - INTERNAL USE ONLY
Region,Revenue,Revenue,Profit Margin
North,"$10,000",500,10%
South,"8,500",,15%
East,12000,600,12%
West,"$15,000",750,8%
TOTAL,45500,1850,
"""
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Generated messy CSV: {filename}")

if __name__ == "__main__":
    create_messy_csv("data/raw/messy_sales_data.csv")