import os
import re
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, KeepTogether
from reportlab.lib.units import inch

# --- 1. DEFINE STYLES ---
styles = getSampleStyleSheet()

styles.add(ParagraphStyle(
    name='BrochureTitle',
    parent=styles['Heading1'],
    fontSize=24,
    textColor=colors.HexColor('#2980b9'),
    spaceAfter=20,
    borderPadding=10,
    borderColor=colors.HexColor('#3498db'),
    borderWidth=0,
    borderBottomWidth=2
))

styles.add(ParagraphStyle(
    name='BrochureH2',
    parent=styles['Heading2'],
    fontSize=18,
    textColor=colors.HexColor('#2c3e50'),
    backColor=colors.HexColor('#ecf0f1'),
    borderPadding=8,
    spaceBefore=20,
    spaceAfter=10
))

styles.add(ParagraphStyle(
    name='BrochureH3',
    parent=styles['Heading3'],
    fontSize=14,
    textColor=colors.HexColor('#34495e'),
    spaceBefore=15,
    spaceAfter=5
))

styles.add(ParagraphStyle(
    name='BrochureBody',
    parent=styles['Normal'],
    fontSize=11,
    leading=14,
    spaceAfter=8
))

styles.add(ParagraphStyle(
    name='BrochureBullet',
    parent=styles['Normal'],
    fontSize=11,
    leading=14,
    leftIndent=20,
    bulletIndent=10,
    spaceAfter=5
))

styles.add(ParagraphStyle(
    name='Caption',
    parent=styles['Normal'],
    fontSize=10,
    textColor=colors.HexColor('#7f8c8d'),
    alignment=1 # Center
))

def make_cover_page(title, subtitle):
    def draw_cover(canvas, doc):
        canvas.saveState()
        canvas.setFillColor(colors.HexColor('#2980b9'))
        canvas.rect(0, A4[1] - 3*inch, A4[0], 3*inch, fill=1, stroke=0)
        
        canvas.setFont('Helvetica-Bold', 26)
        canvas.setFillColor(colors.white)
        canvas.drawCentredString(A4[0]/2, A4[1] - 2*inch, title[:35]) 
        
        canvas.setFont('Helvetica', 16)
        canvas.setFillColor(colors.white)
        canvas.drawCentredString(A4[0]/2, A4[1] - 2.5*inch, subtitle)
        
        canvas.setFont('Helvetica-Oblique', 10)
        canvas.setFillColor(colors.gray)
        canvas.drawCentredString(A4[0]/2, 1*inch, "Generated by GenAI Report Engine")
        canvas.restoreState()
    return draw_cover

def clean_markdown_formatting(text):
    if not text: return ""
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = text.replace('< ', '&lt; ').replace(' >', ' &gt;')
    return text

def convert_markdown_to_pdf_brochure(markdown_text, output_path, images_dir=None, title="Report", subtitle="AI Analysis", chart_list=None):
    """
    Generates a PDF Report.
    - chart_list: A list of tuples [(Description, Path), ...] to append as a Visual Dashboard.
    """
    doc = SimpleDocTemplate(output_path, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    story = []
    
    # 1. Executive Summary Header
    story.append(Spacer(1, 3*inch))
    story.append(Paragraph("Executive Summary", styles['BrochureTitle'])) 
    story.append(PageBreak()) 

    # 2. Parse Markdown Text
    lines = markdown_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line: continue
            
        # Basic Markdown Parsing
        p_style = styles['BrochureBody']
        prefix = ""
        clean_line = line

        if line.startswith('# '):
            p_style = styles['BrochureTitle']
            clean_line = line[2:]
        elif line.startswith('## '):
            p_style = styles['BrochureH2']
            clean_line = line[3:]
        elif line.startswith('### '):
            p_style = styles['BrochureH3']
            clean_line = line[4:]
        elif line.startswith('* ') or line.startswith('- '):
            p_style = styles['BrochureBullet']
            clean_line = line[2:]
            prefix = "• "
        
        # Skip image links in text (we will add them manually at the end)
        if "![" in line and "](" in line:
            continue

        if clean_line:
            formatted_text = clean_markdown_formatting(clean_line)
            story.append(Paragraph(f"{prefix}{formatted_text}", p_style))

    # 3. APPEND VISUAL DASHBOARD (The Fix)
    if chart_list and len(chart_list) > 0:
        story.append(PageBreak())
        story.append(Paragraph("Visual Dashboard", styles['BrochureTitle']))
        story.append(Spacer(1, 0.2*inch))
        
        for desc, img_path in chart_list:
            # Clean path for OS
            img_path = img_path.replace('/', os.sep).replace('\\', os.sep)
            
            if os.path.exists(img_path):
                # Keep Title + Image together so they don't split across pages
                content = []
                content.append(Paragraph(desc, styles['BrochureH3']))
                try:
                    # Resize to fit page width (6 inches)
                    im = Image(img_path, width=6*inch, height=3.5*inch)
                    content.append(im)
                    content.append(Spacer(1, 0.5*inch))
                    story.append(KeepTogether(content))
                except Exception as e:
                    story.append(Paragraph(f"[Error rendering image: {desc}]", styles['Caption']))
            else:
                 story.append(Paragraph(f"[Image Missing: {desc}]", styles['Caption']))

    print(f"🎨 Rendering PDF Brochure to: {output_path}")
    doc.build(story, onFirstPage=make_cover_page(title, subtitle))
    return output_path