import os
import re
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, KeepTogether
from reportlab.lib.units import inch

# --- 1. DEFINE PROFESSIONAL STYLES ---
styles = getSampleStyleSheet()

styles.add(ParagraphStyle(
    name='BrochureTitle',
    parent=styles['Heading1'],
    fontSize=26,
    textColor=colors.HexColor('#1e3a8a'), # Dark Blue
    spaceAfter=30,
    alignment=1 # Center
))

styles.add(ParagraphStyle(
    name='BrochureH1',
    parent=styles['Heading2'],
    fontSize=18,
    textColor=colors.HexColor('#2563eb'), # Royal Blue
    borderPadding=10,
    borderWidth=0,
    borderBottomWidth=1,
    borderColor=colors.HexColor('#e5e7eb'),
    spaceBefore=20,
    spaceAfter=15
))

styles.add(ParagraphStyle(
    name='BrochureH2',
    parent=styles['Heading3'],
    fontSize=14,
    textColor=colors.HexColor('#1f2937'), # Dark Gray
    spaceBefore=15,
    spaceAfter=8,
    fontName='Helvetica-Bold'
))

styles.add(ParagraphStyle(
    name='BrochureBody',
    parent=styles['Normal'],
    fontSize=11,
    leading=16, 
    textColor=colors.HexColor('#374151'),
    spaceAfter=10
))

styles.add(ParagraphStyle(
    name='BrochureBullet',
    parent=styles['Normal'],
    fontSize=11,
    leading=16,
    leftIndent=20,
    bulletIndent=10,
    spaceAfter=6,
    textColor=colors.HexColor('#374151'),
))

def make_cover_page(title, subtitle):
    """Draws a professional cover page."""
    def draw_cover(canvas, doc):
        canvas.saveState()
        # Blue Header Bar
        canvas.setFillColor(colors.HexColor('#1e3a8a'))
        canvas.rect(0, A4[1] - 3*inch, A4[0], 3*inch, fill=1, stroke=0)
        
        # Title
        canvas.setFont('Helvetica-Bold', 28)
        canvas.setFillColor(colors.white)
        canvas.drawCentredString(A4[0]/2, A4[1] - 1.8*inch, title[:40]) 
        
        # Subtitle
        canvas.setFont('Helvetica', 16)
        canvas.setFillColor(colors.white)
        canvas.drawCentredString(A4[0]/2, A4[1] - 2.4*inch, subtitle)
        
        # Footer
        canvas.setFont('Helvetica-Oblique', 10)
        canvas.setFillColor(colors.gray)
        canvas.drawCentredString(A4[0]/2, 0.5*inch, "Generated by GenAI Report Engine")
        canvas.restoreState()
    return draw_cover

def clean_markdown_formatting(text):
    """
    Cleans text for PDF generation.
    1. Converts Markdown bold/italics to XML.
    2. 🟢 STRIPS EMOJIS (Fixes the Black Square/Tofu issue).
    """
    if not text: return ""

    # 🟢 NEW: Remove non-ASCII characters (Emojis, Special Symbols)
    # This keeps standard text, numbers, and punctuation but removes 🚀, 💰, etc.
    text = text.encode('ascii', 'ignore').decode('ascii')

    # Bold: **text** -> <b>text</b>
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    # Italics: *text* -> <i>text</i>
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    
    return text.strip()

def convert_markdown_to_pdf_brochure(markdown_text, output_path, images_dir=None, title="Report", subtitle="AI Analysis", chart_list=None):
    """
    Generates a clean PDF Report.
    """
    doc = SimpleDocTemplate(output_path, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    story = []
    
    # 1. ADD SPACER
    story.append(Spacer(1, 3.5*inch))

    # 2. PARSE MARKDOWN TEXT
    lines = markdown_text.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line: continue
        
        # Skip image links
        if "![" in line and "](" in line: continue

        # --- HEADING DETECTION ---
        if line.startswith('# '):
            story.append(Paragraph(clean_markdown_formatting(line[2:]), styles['BrochureTitle']))
            story.append(Spacer(1, 10))
        elif line.startswith('## '):
            story.append(Paragraph(clean_markdown_formatting(line[3:]), styles['BrochureH1']))
        elif line.startswith('### '):
            story.append(Paragraph(clean_markdown_formatting(line[4:]), styles['BrochureH2']))
        
        # --- LIST DETECTION ---
        elif line.startswith('- ') or line.startswith('* '):
            clean_line = clean_markdown_formatting(line[2:])
            story.append(Paragraph(f"• {clean_line}", styles['BrochureBullet']))
            
        # --- NORMAL TEXT ---
        else:
            clean_line = clean_markdown_formatting(line)
            story.append(Paragraph(clean_line, styles['BrochureBody']))

    # 3. APPEND VISUAL DASHBOARD
    if chart_list and len(chart_list) > 0:
        story.append(PageBreak())
        story.append(Paragraph("Visual Evidence & Analytics", styles['BrochureTitle']))
        story.append(Spacer(1, 20))
        
        for desc, img_path in chart_list:
            img_path = img_path.replace('/', os.sep).replace('\\', os.sep)
            
            if os.path.exists(img_path):
                content = []
                content.append(Paragraph(clean_markdown_formatting(desc), styles['BrochureH2']))
                try:
                    img_width = 6 * inch
                    im = Image(img_path, width=img_width, height=3.5*inch) 
                    im.hAlign = 'CENTER'
                    content.append(im)
                    content.append(Spacer(1, 20))
                    story.append(KeepTogether(content))
                except Exception:
                    pass
            else:
                 story.append(Paragraph(f"[Image Missing: {desc}]", styles['BrochureBody']))

    # 4. BUILD PDF
    print(f"🎨 Rendering Professional PDF to: {output_path}")
    try:
        doc.build(story, onFirstPage=make_cover_page(title, subtitle))
    except Exception as e:
        print(f"⚠️ PDF Build Error: {e}")
        
    return output_path