import os
import re
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, 
    PageBreak, KeepTogether, Table, TableStyle
)
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER, TA_LEFT

# --- 1. CORPORATE BRANDING STYLES ---
styles = getSampleStyleSheet()

COLOR_PRIMARY = colors.HexColor('#0f172a')   # Slate 900
COLOR_ACCENT  = colors.HexColor('#2563eb')   # Royal Blue
COLOR_BG_HEADER = colors.HexColor('#f1f5f9') # Light Slate

# Title Style (Cover Page)
styles.add(ParagraphStyle(
    name='CoverTitle',
    fontName='Helvetica-Bold',
    fontSize=26,
    leading=30,
    textColor=COLOR_PRIMARY,
    alignment=TA_CENTER,
    spaceAfter=20
))

styles.add(ParagraphStyle(
    name='CoverSubtitle',
    fontName='Helvetica',
    fontSize=16,
    textColor=colors.gray,
    alignment=TA_CENTER,
    spaceAfter=50
))

# Header Styles
styles.add(ParagraphStyle(
    name='ReportH1',
    parent=styles['Heading1'],
    fontName='Helvetica-Bold',
    fontSize=18,
    leading=22,
    textColor=COLOR_ACCENT,
    spaceBefore=20,
    spaceAfter=10,
    borderPadding=10,
    borderWidth=0,
    borderBottomWidth=1,
    borderColor=colors.HexColor('#e2e8f0'),
    keepWithNext=True
))

styles.add(ParagraphStyle(
    name='ReportH2',
    parent=styles['Heading2'],
    fontName='Helvetica-Bold',
    fontSize=14,
    leading=18,
    textColor=COLOR_PRIMARY,
    spaceBefore=15,
    spaceAfter=8,
    keepWithNext=True
))

# Body Text
styles.add(ParagraphStyle(
    name='ReportBody',
    parent=styles['Normal'],
    fontName='Helvetica',
    fontSize=10,
    leading=15,
    alignment=TA_JUSTIFY,
    textColor=colors.HexColor('#334155'),
    spaceAfter=10
))

# Bullet Points
styles.add(ParagraphStyle(
    name='ReportBullet',
    parent=styles['Normal'],
    fontSize=10,
    leading=15,
    leftIndent=20,
    bulletIndent=10,
    spaceAfter=5,
    textColor=colors.HexColor('#334155'),
))

def clean_text(text):
    """
    Sanitizes text for PDF generation using ReportLab.
    1. Escapes XML special characters (&, <, >)
    2. Converts Markdown Bold (**) to HTML <b> tags properly.
    """
    if not text: return ""
    
    # 1. Strip Non-ASCII characters (Emojis)
    text = text.encode('ascii', 'ignore').decode('ascii').strip()
    
    # 2. Escape XML characters (CRITICAL FIX)
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    
    # 3. Safe Regex Replacement for Bold/Italics
    # Replaces **text** with <b>text</b>
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    # Replaces *text* with <i>text</i>
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    
    return text

def parse_markdown_table(table_lines):
    """
    Converts raw text lines into a ReportLab Table object with styling.
    """
    data = []
    for line in table_lines:
        if '---' in line: continue 
        # Clean cell content using our safe function
        row = [clean_text(cell) for cell in line.strip().strip('|').split('|')]
        data.append(row)
    
    if not data: return None

    # Auto-width calculation
    col_width = (A4[0] - 2.5*inch) / len(data[0]) 

    t = Table(data, colWidths=[col_width]*len(data[0]))
    
    # PROFESSIONAL TABLE STYLING
    style = TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COLOR_BG_HEADER),
        ('TEXTCOLOR', (0,0), (-1,0), COLOR_ACCENT),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('BOTTOMPADDING', (0,0), (-1,0), 8),
        ('TOPPADDING', (0,0), (-1,0), 8),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f8fafc')]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ])
    t.setStyle(style)
    return t

def header_footer(canvas, doc):
    """Adds branding and page numbers."""
    canvas.saveState()
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(colors.gray)
    
    page_num = canvas.getPageNumber()
    text = "Strategic AI Analysis | Generated by GenAI Engine"
    
    canvas.drawString(inch, 0.75 * inch, text)
    canvas.drawRightString(A4[0] - inch, 0.75 * inch, f"Page {page_num}")
    
    canvas.setStrokeColor(colors.HexColor('#e2e8f0'))
    canvas.line(inch, A4[1] - 0.75*inch, A4[0]-inch, A4[1] - 0.75*inch)
    
    canvas.restoreState()

def convert_markdown_to_pdf_brochure(markdown_text, output_path, images_dir=None, title="Strategic Report", chart_list=None):
    """
    Main PDF Generator Function.
    """
    print(f"🎨 Rendering Professional PDF to: {output_path}")
    doc = SimpleDocTemplate(
        output_path, 
        pagesize=A4,
        rightMargin=inch, leftMargin=inch, topMargin=inch, bottomMargin=inch
    )
    
    story = []

    # --- 1. COVER PAGE ---
    story.append(Spacer(1, 2*inch))
    story.append(Paragraph(title, styles['CoverTitle']))
    story.append(Paragraph("AI-Powered Financial Intelligence", styles['CoverSubtitle']))
    story.append(Spacer(1, 3*inch))
    story.append(Paragraph("Confidential & Proprietary", styles['ReportBody']))
    story.append(PageBreak())

    # --- 2. PARSE CONTENT ---
    lines = markdown_text.split('\n')
    table_buffer = []
    
    for line in lines:
        line = line.strip()
        if not line: continue

        # TABLE LOGIC
        if line.startswith('|'):
            table_buffer.append(line)
            continue
        else:
            if table_buffer:
                t = parse_markdown_table(table_buffer)
                if t: 
                    story.append(Spacer(1, 10))
                    story.append(t)
                    story.append(Spacer(1, 15))
                table_buffer = []

        # HEADERS
        if line.startswith('#'):
            level = line.count('#')
            text = clean_text(line.replace('#', ''))
            style = styles['ReportH1'] if level <= 2 else styles['ReportH2']
            story.append(Paragraph(text, style))

        # BULLET POINTS
        elif line.startswith('- ') or line.startswith('* '):
            text = clean_text(line[2:])
            if ':' in text: # Bold Highlight logic
                parts = text.split(':', 1)
                text = f"<b>{parts[0]}:</b>{parts[1]}"
            story.append(Paragraph(f"• {text}", styles['ReportBullet']))

        # SKIP MARKDOWN IMAGES (We add them at the end)
        elif line.startswith('![') and '](' in line:
            continue

        # NORMAL TEXT
        else:
            story.append(Paragraph(clean_text(line), styles['ReportBody']))

    # Flush remaining table
    if table_buffer:
        t = parse_markdown_table(table_buffer)
        if t: story.append(t)

    # --- 3. VISUAL APPENDIX ---
    if chart_list:
        story.append(PageBreak())
        story.append(Paragraph("Visual Evidence & Analytics", styles['ReportH1']))
        story.append(Spacer(1, 15))

        for desc, img_path in chart_list:
            if os.path.exists(img_path):
                block = []
                block.append(Paragraph(clean_text(desc), styles['ReportH2']))
                try:
                    img = Image(img_path)
                    img_width = 6 * inch
                    aspect = img.imageHeight / float(img.imageWidth)
                    img.drawHeight = img_width * aspect
                    img.drawWidth = img_width
                    
                    block.append(img)
                    block.append(Spacer(1, 20))
                    story.append(KeepTogether(block))
                except Exception:
                    pass

    try:
        doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
        print(f"✅ PDF successfully saved: {output_path}")
        return output_path
    except Exception as e:
        print(f"❌ PDF Generation Failed: {e}")
        return None